// import localFont from "next/font/local";
import { Monda, Jura } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/menu/nav";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const monda = Monda({
  variable: "--font-monda",
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const jura = Jura({
  variable: "--font-jura",
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html className='scroll-smooth' lang='en'>
      <body className={`${monda.className} ${jura.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
